### ISSUE TITLE
Relative/absolute file paths don't work in Vite app

### ISSUE THREAD

**Issue by schickling** [btd/rollup-plugin-visualizer#122]
It seems like when using this plugin within a Vite app, it's not possible to provide relative or absolute file paths for the `filename` option (which might be also better named as `filePath`).

E.g. when using the `visualizer({ emitFile: true, filename: '../some-dir/stats.html' })` I'm getting the following error:

```
vite v3.0.4 building for production...
✓ 656 modules transformed.
✓ 4410 modules transformed.
The emitted file "assets/lz4_wasm_bg.2538a547.wasm" overwrites a previously emitted file of the same name.
rendering chunks (4)...[visualizer] The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../tmp/stats.html".

PWA v0.12.3
mode      generateSW
precache  6 entries (3776.16 KiB)
files generated
  dist/sw.js
  dist/workbox-4648a0c1.js
error during build:
Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../tmp/stats.html".
    at error (file:///Users/johndoe/Code/myapp/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at FileEmitter.emitFile (file:///Users/johndoe/Code/myapp/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:15471:24)
    at Object.generateBundle (/Users/johndoe/Code/myapp/node_modules/rollup-plugin-visualizer/dist/plugin/index.js:120:22)
    at async Bundle.generate (file:///Users/johndoe/Code/myapp/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:15972:9)
    at async file:///Users/johndoe/Code/myapp/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:23708:27
    at async catchUnfinishedHookActions (file:///Users/johndoe/Code/myapp/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:23040:20)
    at async doBuild (file:///Users/johndoe/Code/myapp/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:43524:20)
    at async build (file:///Users/johndoe/Code/myapp/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:43347:16)
    at async CAC.<anonymous> (file:///Users/johndoe/Code/myapp/node_modules/vite/dist/node/cli.js:747:9)
```

**Comment by btd** [comment]
It is because of emitFile. Renove it and it will work. Filename option is both filename and path depending options you pass.
I will add more info about emitFile usage

**Comment by schickling** [comment]
Thanks. Seems to work but indeed rather a rough experience.
