### ISSUE TITLE
Fails to work with some plugins

### ISSUE THREAD

**Issue by katyo** [btd/rollup-plugin-visualizer#22]
I tried to use this pretty useful plugin with latest **rollup** (=0.67), but it fails to work:

```
[!] (Plugin at pos 8 plugin) TypeError: Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at buildTree (.../node_modules/rollup-plugin-visualizer/plugin.js:78:10)
    at Promise.resolve.then.then (.../node_modules/rollup-plugin-visualizer/plugin.js:53:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by katyo** [comment]
Ohh...
It seems the crash happens when the "rollup-plugin-gzip" is used.

**Comment by btd** [comment]
Do you have example that i can run and see your result? Very simple example.

**Comment by katyo** [comment]
Yes, it works.
Thanks.
