### ISSUE TITLE
sourcemap: true errors

### ISSUE THREAD

**Issue by schadenn** [btd/rollup-plugin-visualizer#39]
Hi,

if I'm setting sourcemap: true (plugin is placed after uglify plugin), I get the following error:
```
[!] (visualizer plugin) TypeError: Cannot read property 'sections' of null
TypeError: Cannot read property 'sections' of null
    at _factory (C:\ccb\projects\project\node_modules\rollup-plugin-visualizer\node_modules\source-map\lib\source-map-consumer.js:1246:30)
    at new SourceMapConsumer (C:\ccb\projects\project\node_modules\rollup-plugin-visualizer\node_modules\source-map\lib\source-map-consumer.js:26:12)
    at Function.with (C:\ccb\projects\project\node_modules\rollup-plugin-visualizer\node_modules\source-map\lib\source-map-consumer.js:74:21)
    at addMinifiedSizesToModules (C:\ccb\projects\project\node_modules\rollup-plugin-visualizer\plugin\sourcemap.js:72:32)
    at Object.generateBundle (C:\ccb\projects\project\node_modules\rollup-plugin-visualizer\plugin\index.js:49:17)
    at Promise.resolve.then (C:\ccb\projects\project\node_modules\rollup\dist\rollup.js:15429:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Sadly I can not provide a repro as it's a huge client project with a huge rollup setup. Does the error ring a bell maybe?

Thanks in advance

**Comment by btd** [comment]
Maybe you do not have rollup or some plugins to produce sourcemap?

Is it possible to share rollup config/options you use?

**Comment by schadenn** [comment]
This is the whole rollup.config:
```
module.exports = {
  input: "src/index.jsx",
  inlineDynamicImports: true,
  plugins: [
    json(),
    postcss({
      plugins: [postcssImport(), postcssUrl({ url: "inline" })],
      minimize: true,
      extensions: [".css"]
    }),
    url({
      limit: 10 * 1024, // inline files < 10k, copy files > 10k
      emitFiles: true // defaults to true
    }),
    {
      async transform(code, id) {
        if (id.includes("webcomponents\\dist\\esm\\polyfills\\core-js")) return code.split("//!fetch")[0];
      }
    },
    resolveLazyLoadedComponents(), // this is a selfmade plugin inlining some dynamic dependencies that rollup can't resolve itself
    replace({
      "process.env.NODE_ENV": JSON.stringify("production")
    }),
    resolve({
      dedupe: ["react", "react-dom"],
      extensions: [".mjs", ".js", ".jsx", ".json"]
    }),
    commonjs({
      include: "node_modules/**/*",
      namedExports: {
        "node_modules/stickyfilljs/dist/stickyfill.js": ["addOne", "removeOne"],
        "node_modules/react/index.js": [
          "Children",
          "Component",
          "PropTypes",
          "createElement",
          "createRef",
          "Fragment",
          "cloneElement",
          "PureComponent",
          "createContext",
          "forwardRef"
        ],
        "node_modules/react-is/index.js": ["isFragment"],
        "node_modules/react-dom/index.js": ["render", "findDOMNode"],
        "node_modules/@material/slider/dist/mdc.slider.js": ["MDCSlider"],
        "node_modules/lodash/lodash.js": ["omit", "map"]
      }
    }),
    builtins({ crypto: true }),
    globals(),
    babel({
      include: ["node_modules/**/*", "src/**", "test/**"],
      presets: [
        "@babel/preset-react",
        [
          "@babel/preset-env",
          {
            modules: false,
            spec: true,
            forceAllTransforms: true,
            useBuiltIns: "false",
            corejs: 3,
            targets: {
              browsers: ["ie >= 10", "Firefox >= 60", "Chrome >= 41"]
            }
          }
        ]
      ],
      plugins: [
        "@babel/plugin-proposal-object-rest-spread",
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-syntax-dynamic-import"
      ]
    }),
    isProd &&
    visualizer({
      filename: path.resolve(`${__dirname}/stats.html`),
      open: true
    }),
    uglify(),
    html({
      template: "public/index.html",
      filename: "index.html"
    })
  ],
  output: {
    file: "dist/bundle.js",
    format: "cjs"
  }
};
```

**Comment by btd** [comment]
I think you need to add `output.sourcemap = true` (it is rollup own option). I will try experiment tomorrow to see if can reproduce it.

**Comment by btd** [comment]
Sorry i forgot i will at trip this week, i will take a look only next week

**Comment by schadenn** [comment]
Thanks for the very fast responses. :)

Setting output.sourcemap: true did "work". I don't get any build-time errors anymore. Sadly the stats just show a bundle with NaN as the size and I don't see any modules or anything.

**Comment by btd** [comment]
I tried to add babel + uglify steps, and still could not reproduce it.

**Comment by btd** [comment]
Best i can do for now it is add a plugin warning when sourcemap: true and output.sourcemap missing or false.
If you could prepare me reproducible example i can continue investigate.
