### ISSUE TITLE
show all project bundles in one coherent graph rather than one graph per bundle

### ISSUE THREAD

**Issue by evdama** [btd/rollup-plugin-visualizer#46]
Hi,

I'm doing a svelte/sapper project where I have three section (client, server, service worker). If I add visualizer it only creates stats for the last one (service worker) and not a combined view on my entire project including client, server and service worker sections. Here's my rollup config
https://gist.github.com/1af34bfab3b692cabbeb923bf80b2d9b

As can be seen from lines 107, 162 and 197 it's added to all sections but only results of line 192 are shown.

What do I need to do in order to see the entirety of my project in one graph?

**Comment by btd** [comment]
Hi.

In your case it looks problem in several configs. They all uses the same
file name for visualizer plugin. Just set them in each section different
`filename`.

вс, 22 сент. 2019 г., 9:56 Markus <notifications@github.com>:

**Comment by evdama** [comment]
ah, ok, I see what you mean... but can I then also have a collective graph showing all of my three bundles at once?

**Comment by evdama** [comment]
integrated your suggestions https://gist.github.com/41a08d91b2a8e4c2c5a34c5abed71c51

Now I have three files, one for each of my three bundles. That's great. The cherry on top would still be to have one coherent graph with all three bundles included :)

![Screen Shot 2019-09-22 at 11 18 52](https://user-images.githubusercontent.com/39374084/65385236-a18a3680-dd2c-11e9-886e-92062cc3f3ca.png)

**Comment by btd** [comment]
I worry it is not possible, because you have named configurations in config. My plugin have support of multiple inputs like this (or dynamic chunks):
```
export default {
  input: {
    client: ....,
    server: ....,
    serviceWorker: ....
  }
}
```

In you case it is:
```
export default {
client: ....,
server: ....,
serviceWorker: ....
}
```
In your case plugin do not have access to other named configurations, because they are literally separate.

**Comment by btd** [comment]
Any updates?

**Comment by evdama** [comment]
No updates, I decided to live on with three separate files as shown above. You can close if you want. Thanks!

**Comment by btd** [comment]
Hey @evdama  just in case you are still interested i added fix for use case. You make plugin to produce json and after all your 3 builds completed to generate html with cli util.

**Comment by evdama** [comment]
I upgraded to 3.0.0 and now I get this error
```js
Cannot set property 'id' of undefined
TypeError: Cannot set property 'id' of undefined
    at Object.generateBundle (/Users/sa/0/edm/node_modules/rollup-plugin-visualizer/plugin/index.js:100:23)
    at /Users/sa/0/edm/node_modules/rollup/dist/rollup.js:12842:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by btd** [comment]
That is actually interesting. This could happen if code have imported something that is not included in bundle (at least by info provided by rollup). I just published 3.0.1. Could you also take a look in any logs related to plugin. This could be helpful to understand what is missing. Also `bundlesRelative` removed as this is now default behaviour and template is treemap by default.

**Comment by btd** [comment]
Also when we can make it working you will need to add `json: true` to plugin config (and change filename). After the build something like this `rollup-plugin-visualizer --title "Your title" file1.json file2.json file3.json`

**Comment by evdama** [comment]
```
> Cannot set property 'isExternal' of undefined
TypeError: Cannot set property 'isExternal' of undefined
    at addLinks (/Users/sa/0/edm/node_modules/rollup-plugin-visualizer/plugin/data.js:104:22)
    at Object.generateBundle (/Users/sa/0/edm/node_modules/rollup-plugin-visualizer/plugin/index.js:91:9)
    at /Users/sa/0/edm/node_modules/rollup/dist/rollup.js:12842:25
copying build folder to functions
```
that's with 3.0.1 and the config as in the gist above.

**Comment by btd** [comment]
Published 3.0.4. Just in case do you use dynamic imports?

**Comment by evdama** [comment]
yes, that's working now.

**Comment by evdama** [comment]
> rollup-plugin-visualizer --title "Your title" file1.json file2.json file3.json

ok, got it now... how do I specify an output file?

**Comment by btd** [comment]
Great it started works. First answering questions:
> how do you actually trigger the cli util?
All node js executables stored in ./node_modules/.bin (i added this entry to my PATH). So you can do it like:
```sh
./node_modules/.bin/rollup-plugin-visualizer [OPTIONS] files
```
> honor title: Client Bundle anymore?
Yes i dropped this, not yet sure if it is need. I would like to keep only functional peaces of UI.

> about filename
use --filename (try to call --help it will show all options).

Questions about what you say about autoscale. I tried to make svg to scale to full page height. If it does not work for you this is a bug, can you please share your .html/.json file and tell me in which browser you see it (i test only ff and chrome on windows). It it safe to share as it does not contain your source code (or just send it directly to my email).

**Comment by evdama** [comment]
```
sa@mbp: ~/0/edm/visualizer_stats  |master U:3 ✗| ls -l
total 400
-rw-r--r--  1 sa  staff   82802 Nov 14 21:04 client.json
-rw-r--r--  1 sa  staff  112022 Nov 14 21:04 server.json
-rw-r--r--  1 sa  staff     785 Nov 14 21:04 service-worker.json
sa@mbp: ~/0/edm/visualizer_stats  |master U:3 ✗| ../node_modules/.bin/rollup-plugin-visualizer service-worker.json
Unexpected token o in JSON at position 1
sa@mbp: ~/0/edm/visualizer_stats  |master U:3 ✗|
```
what's going on here?

**Comment by btd** [comment]
There was silly typo. I published 3.0.6

**Comment by evdama** [comment]
yes, that version works. thanks! :)
